Repository tewtal/sm_practice_hack, pull requests merged in 2023-05, with the labels that each got.

#152 Random stuff for v2.5.4
  src/crash.asm
  src/defines.asm
  src/infohud.asm
  src/mainmenu.asm
  src/presets.asm
  src/presets/100early_data.asm
  src/presets/kpdr21_data.asm
  src/presets/pkrd_data.asm
  src/presets/prkd_data.asm
  src/ramwatchmenu.asm
  src/rng.asm
  tools/sm_teledump.lua
  web/data/changelog.mdx
  web/data/config.json
  web/data/help.mdx
Labels: bug, request

#154 Next update [2.5.4]
  build/Debugging_Symbols.sym
  src/crash.asm
  src/defines.asm
  src/infohud.asm
  src/infohudmodes.asm
  src/main.asm
  src/mainmenu.asm
  src/menu.asm
  src/presets.asm
  src/presets/100early_data.asm
  src/presets/kpdr21_data.asm
  src/presets/pkrd_data.asm
  src/presets/prkd_data.asm
  src/ramwatchmenu.asm
  src/rng.asm
  tools/sm_teledump.lua
  web/data/changelog.mdx
  web/data/config.json
  web/data/help.mdx
  web/data/infohudmode.mdx
Labels: next-update

#159 Added menu to inspect custom presets
  .gitignore
  build.bat
  build.sh
  build_PAL.bat
  build_PAL.sh
  build_dev.bat
  build_dev.sh
  names/create_names.py
  names/default_names.txt
  resources/cm_gfx.bin
  resources/normal.tbl
  src/custompresets.asm
  src/defines.asm
  src/macros.asm
  src/mainmenu.asm
  src/menu.asm
  src/roomnames.asm
Labels: request

#162 Auto-Savestate in Doors + Minor Commits
  resources/HUDfont.tbl
  resources/hudgfx.bin
  resources/mapgfx.bin
  src/crash.asm
  src/cutscenes.asm
  src/defines.asm
  src/gamemode.asm
  src/infohud.asm
  src/infohudmodes.asm
  src/init.asm
  src/mainmenu.asm
  src/misc.asm
  src/presets.asm
  src/presets/pkrd_data.asm
  src/presets/prkd_data.asm
  src/rng.asm
Labels: bug, request

#160 Add option to show projectile sprites as 32x32
  src/defines.asm
  src/gamemode.asm
  src/mainmenu.asm
  src/misc.asm
  src/presets.asm
  src/save.asm
  src/spritefeat.asm
  src/tinystates.asm
Labels: request

#161 v2.5.5 Update
  .gitignore
  build.bat
  build.sh
  build/Debugging_Symbols.sym
  build_PAL.bat
  build_PAL.sh
  build_dev.bat
  build_dev.sh
  names/create_names.py
  names/default_names.txt
  resources/HUDfont.tbl
  resources/cm_gfx.bin
  resources/hudgfx.bin
  resources/mapgfx.bin
  resources/normal.tbl
  src/crash.asm
  src/customizemenu.asm
  src/cutscenes.asm
  src/defines.asm
  src/gamemode.asm
  src/infohud.asm
  src/infohudmodes.asm
  src/init.asm
  src/macros.asm
  src/main.asm
  src/mainmenu.asm
  src/menu.asm
  src/misc.asm
  src/presets.asm
  src/presets/pkrd_data.asm
  src/presets/prkd_data.asm
  src/rng.asm
  src/roomnames.asm
  src/save.asm
  src/spritefeat.asm
  src/tinystates.asm
  web/data/changelog.mdx
  web/data/config.json
  web/data/help.mdx
  web/data/infohudmode.mdx
Labels: next-update
