Repository tewtal/sm_practice_hack, pull requests merged in 2023-08, with the labels that each got.

#175 Downback zeb skip room strat
  src/defines.asm
  src/infohudmodes.asm
  src/mainmenu.asm
  web/data/infohudmode.mdx
Labels: request

#176 Small custom preset upgrades, plus misc commits
  src/crash.asm
  src/customizemenu.asm
  src/gamemode.asm
  src/infohud.asm
  src/mainmenu.asm
  src/menu.asm
  src/misc.asm
  src/presets.asm
  src/presets/gtclassic_data.asm
  src/spritefeat.asm
Labels: bug, request

#178 Update 2.5.7 Rollup
  .github/workflows/pullrequest.yml
  build/Debugging_Combined.sym
  build/Debugging_Sorted.sym
  build/Debugging_Symbols.sym
  build_dev.sh
  resources/HUDfont.tbl
  src/crash.asm
  src/customizemenu.asm
  src/defines.asm
  src/gamemode.asm
  src/infohud.asm
  src/infohudmodes.asm
  src/main.asm
  src/mainmenu.asm
  src/menu.asm
  src/misc.asm
  src/presets.asm
  src/presets/gtclassic_data.asm
  src/spritefeat.asm
  web/data/changelog.mdx
  web/data/config.json
  web/data/help.mdx
  web/data/infohudmode.mdx
Labels: next-update

#179 Manage custom presets + misc commits
  src/crash.asm
  src/cutscenes.asm
  src/defines.asm
  src/infohud.asm
  src/macros.asm
  src/mainmenu.asm
  src/menu.asm
  src/presets.asm
  src/symbols.asm
  web/data/help.mdx
Labels: bug, request

#181 Next update v2.5.8
  build.bat
  build.sh
  build/Debugging_Combined.sym
  build/Debugging_Sorted.sym
  build/Debugging_Symbols.sym
  build_PAL.bat
  build_PAL.sh
  build_dev.bat
  build_dev.sh
  layout/create_layout.py
  layout/layoutmenutemplate.asm
  layout/portals.txt
  src/cutscenes.asm
  src/damage.asm
  src/defines.asm
  src/infohudmodes.asm
  src/layout.asm
  src/layoutmenu.asm
  src/layoutportaltables.asm
  src/macros.asm
  src/main.asm
  src/mainmenu.asm
  src/menu.asm
  src/minimap.asm
  src/presets.asm
  src/symbols.asm
  src/tilegraphics.asm
  web/data/changelog.mdx
  web/data/config.json
  web/data/help.mdx
  web/data/infohudmode.mdx
Labels: next-update
